source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 8.8'
end
target 'Unity-iPhone' do
end
use_frameworks!
